puts "The students of Villains Academy"
puts "-----"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Kruger"
puts "The Joker"
puts "Joffrey Barathron"
puts "Norman Bates"

print "\nOverall, we have "
print 11
print " great students"